::: {.callout-important}
## This is a work in progress

Comeback later to see more or, if you want to contribute, open an issue in the associated repo.
:::

This website compiles a series of tutorials, scripts and in general a comprehensive documentation around the [GSI system V3.7 - EnKF V1.3](https://dtcenter.org/community-code/gridpoint-statistical-interpolation-gsi). It focus on the use of GSI as a observation operator along with the LETKF version. It covers everything you need from how to deal with observations (in bufr format), how to configure the system to how read and interpret GSI outputs.  

## A note about using this material

While the text in this guide is released under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/), specific scripts or programming routines may have different licences and authors. If you use the material in any way, make sure to check the Licence note associated to each section and cite it appropriately. 

## Citing this guide

You can cite this guide using its Zenodo metadata and DOI <TBD>.

## Do you want to contribute?

Any contribution is welcome, please read [this guide](contribute.qmd) to learn how to do it. 